services:
  app:
    build: .
    container_name: wasel_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: wasel_db
    restart: "no"

  db:
    image: mysql:8
    container_name: wasel_db
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wasel_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: